// Acceptance generator: .feature -> IR json -> C++ scenario table + CTest registrations.
import fs from 'node:fs';
import path from 'node:path';
import { parseFeatureDir, scanStepDefinitions, bindSteps } from './gherkin.mjs';
import { ensureDir, writeJson, toPosix } from './util.mjs';

const cstr = (s) => {
  if (s == null) return 'nullptr';
  let out = '"';
  for (const ch of String(s)) {
    const c = ch.codePointAt(0);
    if (ch === '"') out += '\\"';
    else if (ch === '\\') out += '\\\\';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\r') out += '\\r';
    else if (ch === '\t') out += '\\t';
    else if (c < 0x20) out += `\\x${c.toString(16).padStart(2, '0')}""`;
    else if (ch === '?') out += '\\?'; // avoid trigraphs
    else out += ch;
  }
  return `${out}"`;
};

export function loadAcceptance(cfg) {
  const features = parseFeatureDir(cfg.abs(cfg.features));
  const defs = scanStepDefinitions(cfg.abs(cfg.stepsDir));
  const binding = bindSteps(features, defs);
  return { features, defs, binding };
}

export function irOf(cfg, features) {
  return {
    generatedBy: 'gauntlet',
    features: features.map((f) => ({
      file: toPosix(path.relative(cfg.root, f.file)),
      name: f.name,
      description: f.description,
      tags: f.tags,
      scenarios: f.scenarios.map((s) => ({ ...s, steps: s.steps.map((st) => ({ ...st })) })),
    })),
  };
}

export function generate(cfg) {
  const { features, defs, binding } = loadAcceptance(cfg);
  const ir = irOf(cfg, features);
  const genDir = ensureDir(cfg.abs(cfg.generatedDir));
  writeJson(path.join(genDir, 'acceptance.ir.json'), ir);

  const lines = [
    '// GENERATED by .gauntlet/gauntlet.mjs gen -- do not edit. Edit features/*.feature instead.',
    '#include "gauntlet_acceptance.hpp"',
    '',
    'static std::vector<gauntlet::Scenario> gauntlet_scenarios() {',
    '  std::vector<gauntlet::Scenario> all;',
  ];
  for (const f of ir.features) {
    for (const s of f.scenarios) {
      lines.push(`  all.push_back({${cstr(s.id)}, ${cstr(f.name)}, ${cstr(s.name)}, ${cstr(`${f.file}:${s.line}`)}, {`);
      for (const st of s.steps) {
        const table = st.table ? `{${st.table.map((r) => `{${r.map(cstr).join(', ')}}`).join(', ')}}` : '{}';
        lines.push(`    {${cstr(st.keyword)}, ${cstr(st.text)}, ${cstr(`${f.file}:${st.line}`)}, ${st.docString == null ? '""' : cstr(st.docString)}, ${st.docString == null ? 'false' : 'true'}, ${table}},`);
      }
      lines.push('  }});');
    }
  }
  lines.push('  return all;', '}', '', 'int main(int argc, char** argv) { return gauntlet::run_main(argc, argv, gauntlet_scenarios()); }', '');
  writeIfChanged(path.join(genDir, 'acceptance_main.cpp'), lines.join('\n'));

  const reportDir = toPosix(cfg.out('acceptance'));
  const cm = ['# GENERATED by .gauntlet/gauntlet.mjs gen -- do not edit.'];
  for (const f of ir.features) for (const s of f.scenarios) {
    cm.push(`add_test(NAME "acc.${s.id}" COMMAND gauntlet_acceptance --scenario "${s.id}" --report-dir "${reportDir}")`);
    cm.push(`set_tests_properties("acc.${s.id}" PROPERTIES LABELS "acceptance")`);
  }
  writeIfChanged(path.join(genDir, 'acceptance_tests.cmake'), cm.join('\n') + '\n');

  const scenarioCount = ir.features.reduce((n, f) => n + f.scenarios.length, 0);
  return { ir, defs, binding, scenarioCount };
}

function writeIfChanged(file, content) {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return;
  fs.writeFileSync(file, content);
}
